import 'package:flutter/widgets.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static const supportedLocales = [
    Locale('en'),
    Locale('ar'),
    Locale('es'),
    Locale('fr'),
    Locale('de'),
    Locale('ru'),
    Locale('zh'),
    Locale('ja'),
    Locale('ko'),
    Locale('pt'),
    Locale('it'),
    Locale('nl'),
  ];

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'Home': 'Home',
      'Calendar': 'Calendar',
      'Add': 'Add',
      'Edit': 'Edit',
      'Bookings': 'Bookings',
      'Profile': 'Profile',
      'Settings': 'Settings',
      'Dark Mode': 'Dark Mode',
      'Notifications': 'Notifications',
      'App Language': 'App Language',
      'Language': 'Language',
      'About': 'About',
      'Log Out': 'Log Out',
      'Delete Account': 'Delete Account',
      'Save Changes': 'Save Changes',
      'Save': 'Save',
      'Cancel': 'Cancel',
      'Close': 'Close',
      'Confirm': 'Confirm',
      'Today': 'Today',
      "Today's Pickups": "Today's Pickups",
      "Today's Returns": "Today's Returns",
      'Quick Actions': 'Quick Actions',
      'Add Client': 'Add Client',
      'Add Product': 'Add Product',
      'Add Booking': 'Add Booking',
      'Add a new client to your database': 'Add a new client to your database',
      'Recieve a notification': 'Recieve a notification',
      'Test the notification system': 'Test the notification system',
      'Clients': 'Clients',
      'Employees': 'Employees',
      'Products': 'Products',
      'All Clients': 'All Clients',
      'All Employees': 'All Employees',
      'All Products': 'All Products',
      'No pickups for today.': 'No pickups for today.',
      'No returns for today': 'No returns for today',
      'App Version': 'App Version',
      'Edit Personal Info': 'Edit Personal Info',
      'Profile Updated': 'Profile Updated',
      'Update failed': 'Update failed',
      'Language updated': 'Language updated',
      'Notifications blocked in System Settings':
          'Notifications blocked in System Settings',
      'Home Cards Open Dialog': 'Home cards open dialog',
      'Delete': 'Delete',
      'Yes': 'Yes',
      'No': 'No',
      'Booking Details': 'Booking Details',
      'Client': 'Client',
      'Pickup': 'Pickup',
      'Return': 'Return',
      'Mark as Picked Up': 'Mark as Picked Up',
      'Mark as Returned': 'Mark as Returned',
      'Login': 'Login',
      'Email': 'Email',
      'Password': 'Password',
      'Name': 'Name',
      'Create Account': 'Create Account',
      "Don't have an account? ": "Don't have an account? ",
      "Already have an account? ": "Already have an account? ",
      'Login Successful!': 'Login Successful!',
      'Login Failed': 'Login Failed',
      'Account Created Successfully!': 'Account Created Successfully!',
      'Registration Failed': 'Registration Failed',
    },
    'ar': {
      'Home': 'الرئيسية',
      'Calendar': 'التقويم',
      'Add': 'إضافة',
      'Edit': 'تعديل',
      'Bookings': 'الحجوزات',
      'Profile': 'الملف الشخصي',
      'Settings': 'الإعدادات',
      'Dark Mode': 'الوضع الداكن',
      'Notifications': 'الإشعارات',
      'App Language': 'لغة التطبيق',
      'Language': 'اللغة',
      'About': 'حول',
      'Log Out': 'تسجيل الخروج',
      'Delete Account': 'حذف الحساب',
      'Save Changes': 'حفظ التغييرات',
      'Save': 'حفظ',
      'Cancel': 'إلغاء',
      'Close': 'إغلاق',
      'Confirm': 'تأكيد',
      'Today': 'اليوم',
      "Today's Pickups": 'استلامات اليوم',
      "Today's Returns": 'مرتجعات اليوم',
      'Quick Actions': 'إجراءات سريعة',
      'Add Client': 'إضافة عميل',
      'Add Product': 'إضافة منتج',
      'Add Booking': 'إضافة حجز',
      'Add a new client to your database': 'أضف عميلاً جديداً إلى قاعدة البيانات',
      'Recieve a notification': 'استلام إشعار',
      'Test the notification system': 'اختبار نظام الإشعارات',
      'Clients': 'العملاء',
      'Employees': 'الموظفون',
      'Products': 'المنتجات',
      'All Clients': 'كل العملاء',
      'All Employees': 'كل الموظفين',
      'All Products': 'كل المنتجات',
      'No pickups for today.': 'لا توجد استلامات اليوم',
      'No returns for today': 'لا توجد مرتجعات اليوم',
      'App Version': 'إصدار التطبيق',
      'Edit Personal Info': 'تعديل البيانات الشخصية',
      'Profile Updated': 'تم تحديث الملف',
      'Update failed': 'فشل التحديث',
      'Language updated': 'تم تحديث اللغة',
      'Notifications blocked in System Settings':
          'الإشعارات محجوبة في إعدادات النظام',
      'Home Cards Open Dialog': 'بطاقات الصفحة الرئيسية تفتح حوارًا',
      'Delete': 'حذف',
      'Yes': 'نعم',
      'No': 'لا',
      'Booking Details': 'تفاصيل الحجز',
      'Client': 'العميل',
      'Pickup': 'استلام',
      'Return': 'إرجاع',
      'Mark as Picked Up': 'تم الاستلام',
      'Mark as Returned': 'تم الإرجاع',
      'Login': 'تسجيل الدخول',
      'Email': 'البريد الإلكتروني',
      'Password': 'كلمة المرور',
      'Name': 'الاسم',
      'Create Account': 'إنشاء حساب',
      "Don't have an account? ": 'ليس لديك حساب؟ ',
      "Already have an account? ": 'لديك حساب بالفعل؟ ',
      'Login Successful!': 'تم تسجيل الدخول بنجاح',
      'Login Failed': 'فشل تسجيل الدخول',
      'Account Created Successfully!': 'تم إنشاء الحساب بنجاح',
      'Registration Failed': 'فشل التسجيل',
    },
    'es': {
      'Home': 'Inicio',
      'Calendar': 'Calendario',
      'Add': 'Añadir',
      'Edit': 'Editar',
      'Bookings': 'Reservas',
      'Profile': 'Perfil',
      'Settings': 'Ajustes',
      'Dark Mode': 'Modo oscuro',
      'Notifications': 'Notificaciones',
      'App Language': 'Idioma de la app',
      'Language': 'Idioma',
      'About': 'Acerca de',
      'Log Out': 'Cerrar sesión',
      'Delete Account': 'Eliminar cuenta',
      'Save Changes': 'Guardar cambios',
      'Save': 'Guardar',
      'Cancel': 'Cancelar',
      'Close': 'Cerrar',
      'Confirm': 'Confirmar',
      'Today': 'Hoy',
      "Today's Pickups": 'Recogidas de hoy',
      "Today's Returns": 'Devoluciones de hoy',
      'Quick Actions': 'Acciones rápidas',
      'Add Client': 'Añadir cliente',
      'Add Product': 'Añadir producto',
      'Add Booking': 'Añadir reserva',
      'Add a new client to your database': 'Añade un nuevo cliente a tu base',
      'Recieve a notification': 'Recibir una notificación',
      'Test the notification system': 'Probar el sistema de notificaciones',
      'Clients': 'Clientes',
      'Employees': 'Empleados',
      'Products': 'Productos',
      'All Clients': 'Todos los clientes',
      'All Employees': 'Todos los empleados',
      'All Products': 'Todos los productos',
      'No pickups for today.': 'No hay recogidas hoy.',
      'No returns for today': 'No hay devoluciones hoy',
      'App Version': 'Versión de la app',
      'Edit Personal Info': 'Editar datos personales',
      'Profile Updated': 'Perfil actualizado',
      'Update failed': 'Falló la actualización',
      'Language updated': 'Idioma actualizado',
      'Notifications blocked in System Settings':
          'Notificaciones bloqueadas en ajustes del sistema',
      'Home Cards Open Dialog': 'Las tarjetas abren un diálogo',
      'Delete': 'Eliminar',
      'Yes': 'Sí',
      'No': 'No',
      'Booking Details': 'Detalles de la reserva',
      'Client': 'Cliente',
      'Pickup': 'Recogida',
      'Return': 'Devolución',
      'Mark as Picked Up': 'Marcar como recogido',
      'Mark as Returned': 'Marcar como devuelto',
      'Login': 'Iniciar sesión',
      'Email': 'Correo',
      'Password': 'Contraseña',
      'Name': 'Nombre',
      'Create Account': 'Crear cuenta',
      "Don't have an account? ": '¿No tienes cuenta? ',
      "Already have an account? ": '¿Ya tienes cuenta? ',
      'Login Successful!': 'Inicio de sesión correcto',
      'Login Failed': 'Error de inicio de sesión',
      'Account Created Successfully!': 'Cuenta creada correctamente',
      'Registration Failed': 'Error de registro',
    },
    'fr': {
      'Home': 'Accueil',
      'Calendar': 'Calendrier',
      'Add': 'Ajouter',
      'Edit': 'Modifier',
      'Bookings': 'Réservations',
      'Profile': 'Profil',
      'Settings': 'Paramètres',
      'Dark Mode': 'Mode sombre',
      'Notifications': 'Notifications',
      'App Language': 'Langue de l’app',
      'Language': 'Langue',
      'About': 'À propos',
      'Log Out': 'Se déconnecter',
      'Delete Account': 'Supprimer le compte',
      'Save Changes': 'Enregistrer',
      'Save': 'Enregistrer',
      'Cancel': 'Annuler',
      'Close': 'Fermer',
      'Confirm': 'Confirmer',
      'Today': 'Aujourd’hui',
      "Today's Pickups": 'Collectes du jour',
      "Today's Returns": 'Retours du jour',
      'Quick Actions': 'Actions rapides',
      'Add Client': 'Ajouter un client',
      'Add Product': 'Ajouter un produit',
      'Add Booking': 'Ajouter une réservation',
      'Add a new client to your database': 'Ajouter un nouveau client',
      'Recieve a notification': 'Recevoir une notification',
      'Test the notification system': 'Tester les notifications',
      'Clients': 'Clients',
      'Employees': 'Employés',
      'Products': 'Produits',
      'All Clients': 'Tous les clients',
      'All Employees': 'Tous les employés',
      'All Products': 'Tous les produits',
      'No pickups for today.': "Aucune collecte aujourd'hui.",
      'No returns for today': "Aucun retour aujourd'hui",
      'App Version': 'Version de l’app',
      'Edit Personal Info': 'Modifier les infos',
      'Profile Updated': 'Profil mis à jour',
      'Update failed': 'Échec de mise à jour',
      'Language updated': 'Langue mise à jour',
      'Notifications blocked in System Settings':
          'Notifications bloquées dans les réglages',
      'Home Cards Open Dialog': 'Cartes d’accueil en dialogue',
      'Delete': 'Supprimer',
      'Yes': 'Oui',
      'No': 'Non',
      'Booking Details': 'Détails de la réservation',
      'Client': 'Client',
      'Pickup': 'Retrait',
      'Return': 'Retour',
      'Mark as Picked Up': 'Marquer comme retiré',
      'Mark as Returned': 'Marquer comme retourné',
      'Login': 'Connexion',
      'Email': 'E-mail',
      'Password': 'Mot de passe',
      'Name': 'Nom',
      'Create Account': 'Créer un compte',
      "Don't have an account? ": "Pas de compte ? ",
      "Already have an account? ": 'Vous avez déjà un compte ? ',
      'Login Successful!': 'Connexion réussie',
      'Login Failed': 'Échec de connexion',
      'Account Created Successfully!': 'Compte créé avec succès',
      'Registration Failed': "Échec de l'inscription",
    },
    'de': {
      'Home': 'Start',
      'Calendar': 'Kalender',
      'Add': 'Hinzufügen',
      'Edit': 'Bearbeiten',
      'Bookings': 'Buchungen',
      'Profile': 'Profil',
      'Settings': 'Einstellungen',
      'Dark Mode': 'Dunkelmodus',
      'Notifications': 'Benachrichtigungen',
      'App Language': 'App-Sprache',
      'Language': 'Sprache',
      'About': 'Über',
      'Log Out': 'Abmelden',
      'Delete Account': 'Konto löschen',
      'Save Changes': 'Änderungen speichern',
      'Save': 'Speichern',
      'Cancel': 'Abbrechen',
      'Close': 'Schließen',
      'Confirm': 'Bestätigen',
      'Today': 'Heute',
      "Today's Pickups": 'Heutige Abholungen',
      "Today's Returns": 'Heutige Rückgaben',
      'Quick Actions': 'Schnellaktionen',
      'Add Client': 'Kunde hinzufügen',
      'Add Product': 'Produkt hinzufügen',
      'Add Booking': 'Buchung hinzufügen',
      'Add a new client to your database': 'Neuen Kunden hinzufügen',
      'Recieve a notification': 'Benachrichtigung erhalten',
      'Test the notification system': 'Benachrichtigungssystem testen',
      'Clients': 'Kunden',
      'Employees': 'Mitarbeiter',
      'Products': 'Produkte',
      'All Clients': 'Alle Kunden',
      'All Employees': 'Alle Mitarbeiter',
      'All Products': 'Alle Produkte',
      'No pickups for today.': 'Keine Abholungen heute.',
      'No returns for today': 'Keine Rückgaben heute',
      'App Version': 'App-Version',
      'Edit Personal Info': 'Persönliche Daten bearbeiten',
      'Profile Updated': 'Profil aktualisiert',
      'Update failed': 'Aktualisierung fehlgeschlagen',
      'Language updated': 'Sprache aktualisiert',
      'Notifications blocked in System Settings':
          'Benachrichtigungen in Systemsettings blockiert',
      'Home Cards Open Dialog': 'Startkarten als Dialog öffnen',
      'Delete': 'Löschen',
      'Yes': 'Ja',
      'No': 'Nein',
      'Booking Details': 'Buchungsdetails',
      'Client': 'Kunde',
      'Pickup': 'Abholung',
      'Return': 'Rückgabe',
      'Mark as Picked Up': 'Als abgeholt markieren',
      'Mark as Returned': 'Als zurückgegeben markieren',
      'Login': 'Anmelden',
      'Email': 'E-Mail',
      'Password': 'Passwort',
      'Name': 'Name',
      'Create Account': 'Konto erstellen',
      "Don't have an account? ": 'Kein Konto? ',
      "Already have an account? ": 'Schon ein Konto? ',
      'Login Successful!': 'Anmeldung erfolgreich',
      'Login Failed': 'Anmeldung fehlgeschlagen',
      'Account Created Successfully!': 'Konto erstellt',
      'Registration Failed': 'Registrierung fehlgeschlagen',
    },
    'ru': {
      'Home': 'Главная',
      'Calendar': 'Календарь',
      'Add': 'Добавить',
      'Edit': 'Редактировать',
      'Bookings': 'Бронирования',
      'Profile': 'Профиль',
      'Settings': 'Настройки',
      'Dark Mode': 'Тёмный режим',
      'Notifications': 'Уведомления',
      'App Language': 'Язык приложения',
      'Language': 'Язык',
      'About': 'О приложении',
      'Log Out': 'Выйти',
      'Delete Account': 'Удалить аккаунт',
      'Save Changes': 'Сохранить',
      'Save': 'Сохранить',
      'Cancel': 'Отмена',
      'Close': 'Закрыть',
      'Confirm': 'Подтвердить',
      'Today': 'Сегодня',
      "Today's Pickups": 'Получения сегодня',
      "Today's Returns": 'Возвраты сегодня',
      'Quick Actions': 'Быстрые действия',
      'Add Client': 'Добавить клиента',
      'Add Product': 'Добавить продукт',
      'Add Booking': 'Добавить бронирование',
      'Add a new client to your database': 'Добавить клиента в базу',
      'Recieve a notification': 'Получить уведомление',
      'Test the notification system': 'Проверить уведомления',
      'Clients': 'Клиенты',
      'Employees': 'Сотрудники',
      'Products': 'Продукты',
      'All Clients': 'Все клиенты',
      'All Employees': 'Все сотрудники',
      'All Products': 'Все продукты',
      'No pickups for today.': 'Сегодня нет выдач.',
      'No returns for today': 'Сегодня нет возвратов',
      'App Version': 'Версия приложения',
      'Edit Personal Info': 'Редактировать данные',
      'Profile Updated': 'Профиль обновлён',
      'Update failed': 'Ошибка обновления',
      'Language updated': 'Язык обновлён',
      'Notifications blocked in System Settings':
          'Уведомления заблокированы в настройках',
      'Home Cards Open Dialog': 'Карты на главной в диалоге',
      'Delete': 'Удалить',
      'Yes': 'Да',
      'No': 'Нет',
      'Booking Details': 'Детали бронирования',
      'Client': 'Клиент',
      'Pickup': 'Получение',
      'Return': 'Возврат',
      'Mark as Picked Up': 'Отметить как получено',
      'Mark as Returned': 'Отметить как возвращено',
      'Login': 'Вход',
      'Email': 'Почта',
      'Password': 'Пароль',
      'Name': 'Имя',
      'Create Account': 'Создать аккаунт',
      "Don't have an account? ": 'Нет аккаунта? ',
      "Already have an account? ": 'Уже есть аккаунт? ',
      'Login Successful!': 'Вход выполнен',
      'Login Failed': 'Ошибка входа',
      'Account Created Successfully!': 'Аккаунт создан',
      'Registration Failed': 'Ошибка регистрации',
    },
    'zh': {
      'Home': '首页',
      'Calendar': '日历',
      'Add': '添加',
      'Edit': '编辑',
      'Bookings': '预订',
      'Profile': '个人资料',
      'Settings': '设置',
      'Dark Mode': '深色模式',
      'Notifications': '通知',
      'App Language': '应用语言',
      'Language': '语言',
      'About': '关于',
      'Log Out': '退出登录',
      'Delete Account': '删除账户',
      'Save Changes': '保存更改',
      'Save': '保存',
      'Cancel': '取消',
      'Close': '关闭',
      'Confirm': '确认',
      'Today': '今天',
      "Today's Pickups": '今日取货',
      "Today's Returns": '今日归还',
      'Quick Actions': '快捷操作',
      'Add Client': '添加客户',
      'Add Product': '添加产品',
      'Add Booking': '添加预订',
      'Add a new client to your database': '新增客户到数据库',
      'Recieve a notification': '接收通知',
      'Test the notification system': '测试通知系统',
      'Clients': '客户',
      'Employees': '员工',
      'Products': '产品',
      'All Clients': '所有客户',
      'All Employees': '所有员工',
      'All Products': '所有产品',
      'No pickups for today.': '今天没有取货。',
      'No returns for today': '今天没有归还',
      'App Version': '应用版本',
      'Edit Personal Info': '编辑个人信息',
      'Profile Updated': '资料已更新',
      'Update failed': '更新失败',
      'Language updated': '语言已更新',
      'Notifications blocked in System Settings': '系统设置中已阻止通知',
      'Home Cards Open Dialog': '主页卡片以对话框打开',
      'Delete': '删除',
      'Yes': '是',
      'No': '否',
      'Booking Details': '预订详情',
      'Client': '客户',
      'Pickup': '取货',
      'Return': '归还',
      'Mark as Picked Up': '标记为已取货',
      'Mark as Returned': '标记为已归还',
      'Login': '登录',
      'Email': '邮箱',
      'Password': '密码',
      'Name': '姓名',
      'Create Account': '创建账户',
      "Don't have an account? ": '没有账户？',
      "Already have an account? ": '已有账户？',
      'Login Successful!': '登录成功',
      'Login Failed': '登录失败',
      'Account Created Successfully!': '账户创建成功',
      'Registration Failed': '注册失败',
    },
    'ja': {
      'Home': 'ホーム',
      'Calendar': 'カレンダー',
      'Add': '追加',
      'Edit': '編集',
      'Bookings': '予約',
      'Profile': 'プロフィール',
      'Settings': '設定',
      'Dark Mode': 'ダークモード',
      'Notifications': '通知',
      'App Language': 'アプリ言語',
      'Language': '言語',
      'About': '概要',
      'Log Out': 'ログアウト',
      'Delete Account': 'アカウント削除',
      'Save Changes': '変更を保存',
      'Save': '保存',
      'Cancel': 'キャンセル',
      'Close': '閉じる',
      'Confirm': '確認',
      'Today': '今日',
      "Today's Pickups": '本日の受取',
      "Today's Returns": '本日の返却',
      'Quick Actions': 'クイック操作',
      'Add Client': '顧客追加',
      'Add Product': '商品追加',
      'Add Booking': '予約追加',
      'Add a new client to your database': '顧客を追加',
      'Recieve a notification': '通知を受け取る',
      'Test the notification system': '通知をテスト',
      'Clients': '顧客',
      'Employees': '従業員',
      'Products': '商品',
      'All Clients': 'すべての顧客',
      'All Employees': 'すべての従業員',
      'All Products': 'すべての商品',
      'No pickups for today.': '本日の受取はありません。',
      'No returns for today': '本日の返却はありません',
      'App Version': 'アプリバージョン',
      'Edit Personal Info': '個人情報を編集',
      'Profile Updated': 'プロフィール更新済み',
      'Update failed': '更新失敗',
      'Language updated': '言語を更新しました',
      'Notifications blocked in System Settings': 'システム設定で通知が無効です',
      'Home Cards Open Dialog': 'ホームカードをダイアログで開く',
      'Delete': '削除',
      'Yes': 'はい',
      'No': 'いいえ',
      'Booking Details': '予約詳細',
      'Client': '顧客',
      'Pickup': '受取',
      'Return': '返却',
      'Mark as Picked Up': '受取済みにする',
      'Mark as Returned': '返却済みにする',
      'Login': 'ログイン',
      'Email': 'メール',
      'Password': 'パスワード',
      'Name': '名前',
      'Create Account': 'アカウント作成',
      "Don't have an account? ": 'アカウントがありませんか？',
      "Already have an account? ": 'すでにアカウントがありますか？',
      'Login Successful!': 'ログイン成功',
      'Login Failed': 'ログイン失敗',
      'Account Created Successfully!': 'アカウント作成完了',
      'Registration Failed': '登録失敗',
    },
    'ko': {
      'Home': '홈',
      'Calendar': '캘린더',
      'Add': '추가',
      'Edit': '편집',
      'Bookings': '예약',
      'Profile': '프로필',
      'Settings': '설정',
      'Dark Mode': '다크 모드',
      'Notifications': '알림',
      'App Language': '앱 언어',
      'Language': '언어',
      'About': '정보',
      'Log Out': '로그아웃',
      'Delete Account': '계정 삭제',
      'Save Changes': '변경 저장',
      'Save': '저장',
      'Cancel': '취소',
      'Close': '닫기',
      'Confirm': '확인',
      'Today': '오늘',
      "Today's Pickups": '오늘 픽업',
      "Today's Returns": '오늘 반납',
      'Quick Actions': '빠른 작업',
      'Add Client': '고객 추가',
      'Add Product': '상품 추가',
      'Add Booking': '예약 추가',
      'Add a new client to your database': '새 고객 추가',
      'Recieve a notification': '알림 받기',
      'Test the notification system': '알림 테스트',
      'Clients': '고객',
      'Employees': '직원',
      'Products': '상품',
      'All Clients': '전체 고객',
      'All Employees': '전체 직원',
      'All Products': '전체 상품',
      'No pickups for today.': '오늘 픽업 없음.',
      'No returns for today': '오늘 반납 없음',
      'App Version': '앱 버전',
      'Edit Personal Info': '개인정보 수정',
      'Profile Updated': '프로필 업데이트됨',
      'Update failed': '업데이트 실패',
      'Language updated': '언어가 업데이트되었습니다',
      'Notifications blocked in System Settings': '시스템 설정에서 알림이 차단됨',
      'Home Cards Open Dialog': '홈 카드 대화상자로 열기',
      'Delete': '삭제',
      'Yes': '예',
      'No': '아니요',
      'Booking Details': '예약 상세',
      'Client': '고객',
      'Pickup': '픽업',
      'Return': '반납',
      'Mark as Picked Up': '픽업 완료',
      'Mark as Returned': '반납 완료',
      'Login': '로그인',
      'Email': '이메일',
      'Password': '비밀번호',
      'Name': '이름',
      'Create Account': '계정 만들기',
      "Don't have an account? ": '계정이 없나요? ',
      "Already have an account? ": '이미 계정이 있나요? ',
      'Login Successful!': '로그인 성공',
      'Login Failed': '로그인 실패',
      'Account Created Successfully!': '계정 생성 완료',
      'Registration Failed': '등록 실패',
    },
    'pt': {
      'Home': 'Início',
      'Calendar': 'Calendário',
      'Add': 'Adicionar',
      'Edit': 'Editar',
      'Bookings': 'Reservas',
      'Profile': 'Perfil',
      'Settings': 'Configurações',
      'Dark Mode': 'Modo escuro',
      'Notifications': 'Notificações',
      'App Language': 'Idioma do app',
      'Language': 'Idioma',
      'About': 'Sobre',
      'Log Out': 'Sair',
      'Delete Account': 'Excluir conta',
      'Save Changes': 'Salvar alterações',
      'Save': 'Salvar',
      'Cancel': 'Cancelar',
      'Close': 'Fechar',
      'Confirm': 'Confirmar',
      'Today': 'Hoje',
      "Today's Pickups": 'Retiradas de hoje',
      "Today's Returns": 'Devoluções de hoje',
      'Quick Actions': 'Ações rápidas',
      'Add Client': 'Adicionar cliente',
      'Add Product': 'Adicionar produto',
      'Add Booking': 'Adicionar reserva',
      'Add a new client to your database': 'Adicionar novo cliente',
      'Recieve a notification': 'Receber notificação',
      'Test the notification system': 'Testar notificações',
      'Clients': 'Clientes',
      'Employees': 'Funcionários',
      'Products': 'Produtos',
      'All Clients': 'Todos os clientes',
      'All Employees': 'Todos os funcionários',
      'All Products': 'Todos os produtos',
      'No pickups for today.': 'Sem retiradas hoje.',
      'No returns for today': 'Sem devoluções hoje',
      'App Version': 'Versão do app',
      'Edit Personal Info': 'Editar informações',
      'Profile Updated': 'Perfil atualizado',
      'Update failed': 'Falha na atualização',
      'Language updated': 'Idioma atualizado',
      'Notifications blocked in System Settings':
          'Notificações bloqueadas nas configurações',
      'Home Cards Open Dialog': 'Cartões da home em diálogo',
      'Delete': 'Excluir',
      'Yes': 'Sim',
      'No': 'Não',
      'Booking Details': 'Detalhes da reserva',
      'Client': 'Cliente',
      'Pickup': 'Retirada',
      'Return': 'Devolução',
      'Mark as Picked Up': 'Marcar como retirado',
      'Mark as Returned': 'Marcar como devolvido',
      'Login': 'Entrar',
      'Email': 'E-mail',
      'Password': 'Senha',
      'Name': 'Nome',
      'Create Account': 'Criar conta',
      "Don't have an account? ": 'Não tem conta? ',
      "Already have an account? ": 'Já tem conta? ',
      'Login Successful!': 'Login realizado',
      'Login Failed': 'Falha no login',
      'Account Created Successfully!': 'Conta criada com sucesso',
      'Registration Failed': 'Falha no cadastro',
    },
    'it': {
      'Home': 'Home',
      'Calendar': 'Calendario',
      'Add': 'Aggiungi',
      'Edit': 'Modifica',
      'Bookings': 'Prenotazioni',
      'Profile': 'Profilo',
      'Settings': 'Impostazioni',
      'Dark Mode': 'Modalità scura',
      'Notifications': 'Notifiche',
      'App Language': 'Lingua app',
      'Language': 'Lingua',
      'About': 'Informazioni',
      'Log Out': 'Esci',
      'Delete Account': 'Elimina account',
      'Save Changes': 'Salva modifiche',
      'Save': 'Salva',
      'Cancel': 'Annulla',
      'Close': 'Chiudi',
      'Confirm': 'Conferma',
      'Today': 'Oggi',
      "Today's Pickups": 'Ritiri di oggi',
      "Today's Returns": 'Resi di oggi',
      'Quick Actions': 'Azioni rapide',
      'Add Client': 'Aggiungi cliente',
      'Add Product': 'Aggiungi prodotto',
      'Add Booking': 'Aggiungi prenotazione',
      'Add a new client to your database': 'Aggiungi un nuovo cliente',
      'Recieve a notification': 'Ricevere una notifica',
      'Test the notification system': 'Testare le notifiche',
      'Clients': 'Clienti',
      'Employees': 'Dipendenti',
      'Products': 'Prodotti',
      'All Clients': 'Tutti i clienti',
      'All Employees': 'Tutti i dipendenti',
      'All Products': 'Tutti i prodotti',
      'No pickups for today.': 'Nessun ritiro oggi.',
      'No returns for today': 'Nessun reso oggi',
      'App Version': 'Versione app',
      'Edit Personal Info': 'Modifica info personali',
      'Profile Updated': 'Profilo aggiornato',
      'Update failed': 'Aggiornamento fallito',
      'Language updated': 'Lingua aggiornata',
      'Notifications blocked in System Settings':
          'Notifiche bloccate nelle impostazioni',
      'Home Cards Open Dialog': 'Schede home in dialogo',
      'Delete': 'Elimina',
      'Yes': 'Sì',
      'No': 'No',
      'Booking Details': 'Dettagli prenotazione',
      'Client': 'Cliente',
      'Pickup': 'Ritiro',
      'Return': 'Reso',
      'Mark as Picked Up': 'Segna come ritirato',
      'Mark as Returned': 'Segna come restituito',
      'Login': 'Accedi',
      'Email': 'Email',
      'Password': 'Password',
      'Name': 'Nome',
      'Create Account': 'Crea account',
      "Don't have an account? ": 'Non hai un account? ',
      "Already have an account? ": 'Hai già un account? ',
      'Login Successful!': 'Accesso riuscito',
      'Login Failed': 'Accesso fallito',
      'Account Created Successfully!': 'Account creato',
      'Registration Failed': 'Registrazione fallita',
    },
    'nl': {
      'Home': 'Home',
      'Calendar': 'Kalender',
      'Add': 'Toevoegen',
      'Edit': 'Bewerken',
      'Bookings': 'Boekingen',
      'Profile': 'Profiel',
      'Settings': 'Instellingen',
      'Dark Mode': 'Donkere modus',
      'Notifications': 'Meldingen',
      'App Language': 'App-taal',
      'Language': 'Taal',
      'About': 'Over',
      'Log Out': 'Uitloggen',
      'Delete Account': 'Account verwijderen',
      'Save Changes': 'Wijzigingen opslaan',
      'Save': 'Opslaan',
      'Cancel': 'Annuleren',
      'Close': 'Sluiten',
      'Confirm': 'Bevestigen',
      'Today': 'Vandaag',
      "Today's Pickups": 'Ophalen vandaag',
      "Today's Returns": 'Retour vandaag',
      'Quick Actions': 'Snelle acties',
      'Add Client': 'Klant toevoegen',
      'Add Product': 'Product toevoegen',
      'Add Booking': 'Boeking toevoegen',
      'Add a new client to your database': 'Nieuwe klant toevoegen',
      'Recieve a notification': 'Melding ontvangen',
      'Test the notification system': 'Meldingen testen',
      'Clients': 'Klanten',
      'Employees': 'Medewerkers',
      'Products': 'Producten',
      'All Clients': 'Alle klanten',
      'All Employees': 'Alle medewerkers',
      'All Products': 'Alle producten',
      'No pickups for today.': 'Geen afhalingen vandaag.',
      'No returns for today': 'Geen retouren vandaag',
      'App Version': 'App-versie',
      'Edit Personal Info': 'Persoonlijke info bewerken',
      'Profile Updated': 'Profiel bijgewerkt',
      'Update failed': 'Update mislukt',
      'Language updated': 'Taal bijgewerkt',
      'Notifications blocked in System Settings':
          'Meldingen geblokkeerd in systeeminstellingen',
      'Home Cards Open Dialog': 'Homekaarten in dialoog openen',
      'Delete': 'Verwijderen',
      'Yes': 'Ja',
      'No': 'Nee',
      'Booking Details': 'Boekingsdetails',
      'Client': 'Klant',
      'Pickup': 'Ophalen',
      'Return': 'Retour',
      'Mark as Picked Up': 'Markeer als opgehaald',
      'Mark as Returned': 'Markeer als geretourneerd',
      'Login': 'Inloggen',
      'Email': 'E-mail',
      'Password': 'Wachtwoord',
      'Name': 'Naam',
      'Create Account': 'Account aanmaken',
      "Don't have an account? ": 'Nog geen account? ',
      "Already have an account? ": 'Heb je al een account? ',
      'Login Successful!': 'Inloggen gelukt',
      'Login Failed': 'Inloggen mislukt',
      'Account Created Successfully!': 'Account aangemaakt',
      'Registration Failed': 'Registratie mislukt',
    },
  };

  String tr(String key) {
    final code = locale.languageCode;
    final map = _translations[code] ?? _translations['en']!;
    return map[key] ?? _translations['en']![key] ?? key;
  }
}

class AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales.any(
      (l) => l.languageCode == locale.languageCode,
    );
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;
}
