// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEtpdicYuP6aq-vp75EFQ_kpdatRzFCVs',
    appId: '1:941979087552:web:32f091b484383c259ff325',
    messagingSenderId: '941979087552',
    projectId: 'ccr-booking-app1',
    authDomain: 'ccr-booking-app1.firebaseapp.com',
    storageBucket: 'ccr-booking-app1.firebasestorage.app',
    measurementId: 'G-TNJM6BN5CZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNvnkZcHhJ4t9Sd78Qvs5pwa7-4KC-oj8',
    appId: '1:941979087552:android:017b6b578f8637c39ff325',
    messagingSenderId: '941979087552',
    projectId: 'ccr-booking-app1',
    storageBucket: 'ccr-booking-app1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAeF0f2MamJf7qhqegocuRbBsjXGHru6s',
    appId: '1:941979087552:ios:dcdda67fed3910449ff325',
    messagingSenderId: '941979087552',
    projectId: 'ccr-booking-app1',
    storageBucket: 'ccr-booking-app1.firebasestorage.app',
    iosBundleId: 'com.example.database.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAeF0f2MamJf7qhqegocuRbBsjXGHru6s',
    appId: '1:941979087552:ios:6b137e9b153321529ff325',
    messagingSenderId: '941979087552',
    projectId: 'ccr-booking-app1',
    storageBucket: 'ccr-booking-app1.firebasestorage.app',
    iosBundleId: 'com.example.database',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEtpdicYuP6aq-vp75EFQ_kpdatRzFCVs',
    appId: '1:941979087552:web:e163a8134b699ad29ff325',
    messagingSenderId: '941979087552',
    projectId: 'ccr-booking-app1',
    authDomain: 'ccr-booking-app1.firebaseapp.com',
    storageBucket: 'ccr-booking-app1.firebasestorage.app',
    measurementId: 'G-19PQNJM37P',
  );

}